services:
  minio:
    image: minio/minio:RELEASE.2024-06-13T22-53-53Z
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_VOLUMES: /mnt/data
    volumes:
      - ./docker-volume/minio:/mnt/data
      - /etc/localtime:/etc/localtime
    ports:
      - 10001:10001
    command:
      - server
      - --console-address
      - ":10001"
  postgres1:
    image: ghcr.io/zalando/spilo-16:3.2-p3
    restart: always
    volumes:
      - ./docker-volume/postgres1:/home/postgres/pgdata
      - /etc/localtime:/etc/localtime
    ports:
      - 10432:5432
    environment:
      WAL_S3_BUCKET: postgres-backup
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_ENDPOINT: http://minio:9000
      SCOPE: postgres1
  postgres2:
    image: ghcr.io/zalando/spilo-16:3.2-p3
    restart: always
    volumes:
      - ./docker-volume/postgres2:/home/postgres/pgdata
      - /etc/localtime:/etc/localtime
    ports:
      - 10433:5432
    environment:
      CLONE_METHOD: CLONE_WITH_WALE
      CLONE_WAL_S3_BUCKET: postgres-backup
      CLONE_AWS_ACCESS_KEY_ID: admin
      CLONE_AWS_SECRET_ACCESS_KEY: password
      CLONE_AWS_ENDPOINT: http://minio:9000
      CLONE_SCOPE: postgres1
      CLONE_TARGET_TIME: ""
      SCOPE: postgres2
      TZ: Asia/Jakarta